<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251027133432 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "tag" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, color VARCHAR(7) NOT NULL, icon VARCHAR(255) DEFAULT NULL, usage_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_389B783A76ED395 ON "tag" (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_tag_per_user ON "tag" (name, user_id)');
        $this->addSql('CREATE TABLE "task" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sort_order INT NOT NULL, is_archived BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, parent_task_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_527EDB25A76ED395 ON "task" (user_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25FFFE75C0 ON "task" (parent_task_id)');
        $this->addSql('CREATE TABLE task_tags (task_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(task_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_1C0F005D8DB60186 ON task_tags (task_id)');
        $this->addSql('CREATE INDEX IDX_1C0F005DBAD26311 ON task_tags (tag_id)');
        $this->addSql('ALTER TABLE "tag" ADD CONSTRAINT FK_389B783A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "task" ADD CONSTRAINT FK_527EDB25A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "task" ADD CONSTRAINT FK_527EDB25FFFE75C0 FOREIGN KEY (parent_task_id) REFERENCES "task" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_tags ADD CONSTRAINT FK_1C0F005D8DB60186 FOREIGN KEY (task_id) REFERENCES "task" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_tags ADD CONSTRAINT FK_1C0F005DBAD26311 FOREIGN KEY (tag_id) REFERENCES "tag" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "tag" DROP CONSTRAINT FK_389B783A76ED395');
        $this->addSql('ALTER TABLE "task" DROP CONSTRAINT FK_527EDB25A76ED395');
        $this->addSql('ALTER TABLE "task" DROP CONSTRAINT FK_527EDB25FFFE75C0');
        $this->addSql('ALTER TABLE task_tags DROP CONSTRAINT FK_1C0F005D8DB60186');
        $this->addSql('ALTER TABLE task_tags DROP CONSTRAINT FK_1C0F005DBAD26311');
        $this->addSql('DROP TABLE "tag"');
        $this->addSql('DROP TABLE "task"');
        $this->addSql('DROP TABLE task_tags');
    }
}
