<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251103195026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add performance indexes for analytics queries';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recurrence_rules DROP CONSTRAINT fk_recurrence_template_task');
        $this->addSql('DROP INDEX idx_recurrence_active_next');
        $this->addSql('DROP INDEX idx_recurrence_template_task');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id TYPE INT');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recurrence_rules ADD CONSTRAINT FK_6A793260DE0E7ABF FOREIGN KEY (template_task_id) REFERENCES "task" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A793260DE0E7ABF ON recurrence_rules (template_task_id)');
        $this->addSql('ALTER INDEX idx_recurrence_created_by RENAME TO IDX_6A793260B03A8386');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT fk_task_generated_from_rule');
        $this->addSql('DROP INDEX idx_task_is_recurring_template');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25728EDEC3 FOREIGN KEY (generated_from_rule_id) REFERENCES recurrence_rules (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_task_generated_from_rule RENAME TO IDX_527EDB25728EDEC3');
        $this->addSql('ALTER TABLE users ALTER notification_settings TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER notification_settings DROP DEFAULT');

        // Add performance indexes for analytics queries
        $this->addSql('CREATE INDEX idx_task_user_parent ON "task" (user_id, parent_task_id)');
        $this->addSql('CREATE INDEX idx_task_user_status ON "task" (user_id, status)');
        $this->addSql('CREATE INDEX idx_task_user_created_at ON "task" (user_id, created_at)');
        $this->addSql('CREATE INDEX idx_task_user_completed_at ON "task" (user_id, completed_at)');
        $this->addSql('CREATE INDEX idx_task_user_due_date ON "task" (user_id, due_date)');
        $this->addSql('CREATE INDEX idx_task_user_priority ON "task" (user_id, priority)');
        $this->addSql('CREATE INDEX idx_task_user_archived ON "task" (user_id, is_archived)');
        $this->addSql('CREATE INDEX idx_task_user_parent_archived ON "task" (user_id, parent_task_id, is_archived)');
        $this->addSql('CREATE INDEX idx_task_user_parent_status ON "task" (user_id, parent_task_id, status)');
        $this->addSql('CREATE INDEX idx_task_user_parent_created ON "task" (user_id, parent_task_id, created_at)');
        $this->addSql('CREATE INDEX idx_task_user_parent_completed ON "task" (user_id, parent_task_id, completed_at)');
        $this->addSql('CREATE INDEX idx_task_user_sort_order ON "task" (user_id, sort_order)');

        // Tag indexes for analytics
        $this->addSql('CREATE INDEX idx_tag_user_usage ON tag (user_id, usage_count)');
        $this->addSql('CREATE INDEX idx_tag_user_name ON tag (user_id, name)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "users" ALTER notification_settings TYPE JSON');
        $this->addSql('ALTER TABLE "users" ALTER notification_settings SET DEFAULT \'{"email":true,"push":true,"taskReminders":true,"taskAssignments":true,"weeklyDigest":false}\'');
        $this->addSql('ALTER TABLE recurrence_rules DROP CONSTRAINT FK_6A793260DE0E7ABF');
        $this->addSql('DROP INDEX UNIQ_6A793260DE0E7ABF');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id TYPE INT');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id SET DEFAULT recurrence_rules_id_seq');
        $this->addSql('ALTER TABLE recurrence_rules ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recurrence_rules ADD CONSTRAINT fk_recurrence_template_task FOREIGN KEY (template_task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_recurrence_active_next ON recurrence_rules (is_active, next_occurrence_date)');
        $this->addSql('CREATE INDEX idx_recurrence_template_task ON recurrence_rules (template_task_id)');
        $this->addSql('ALTER INDEX idx_6a793260b03a8386 RENAME TO idx_recurrence_created_by');
        $this->addSql('ALTER TABLE "task" DROP CONSTRAINT FK_527EDB25728EDEC3');
        $this->addSql('ALTER TABLE "task" ADD CONSTRAINT fk_task_generated_from_rule FOREIGN KEY (generated_from_rule_id) REFERENCES recurrence_rules (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_task_is_recurring_template ON "task" (is_recurring_template)');
        $this->addSql('ALTER INDEX idx_527edb25728edec3 RENAME TO idx_task_generated_from_rule');

        // Drop performance indexes
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_parent');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_status');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_created_at');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_completed_at');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_due_date');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_priority');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_archived');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_parent_archived');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_parent_status');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_parent_created');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_parent_completed');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_sort_order');
        $this->addSql('DROP INDEX IF EXISTS idx_tag_user_usage');
        $this->addSql('DROP INDEX IF EXISTS idx_tag_user_name');
    }
}
