#!/bin/bash
# scripts/worktree/worktree-create.sh
# Автоматически создает Git worktree с правильной конфигурацией портов и Docker окружения

set -e

BRANCH_NAME=$1
WORKTREE_NAME=$2

if [ -z "$BRANCH_NAME" ] || [ -z "$WORKTREE_NAME" ]; then
    echo "❌ Использование: ./worktree-create.sh <branch-name> <worktree-name>"
    echo ""
    echo "Примеры:"
    echo "  ./worktree-create.sh feature/new-api feature-new-api"
    echo "  ./worktree-create.sh feature/caching feature-caching"
    exit 1
fi

MAIN_DIR="/Users/sollent/Desktop/Projects/CLAUDE"
WORKTREE_DIR="/Users/sollent/Desktop/Projects/CLAUDE-worktrees/$WORKTREE_NAME"

echo "🌳 Создание worktree для ветки: $BRANCH_NAME"
echo "📂 Директория worktree: $WORKTREE_DIR"

# Создаем директорию для worktrees если не существует
mkdir -p /Users/sollent/Desktop/Projects/CLAUDE-worktrees

# Переходим в main репозиторий
cd "$MAIN_DIR"

# Проверяем существует ли ветка
if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
    echo "✅ Ветка существует, создаем worktree..."
    git worktree add "$WORKTREE_DIR" "$BRANCH_NAME"
elif git show-ref --verify --quiet refs/remotes/origin/"$BRANCH_NAME"; then
    echo "✅ Ветка существует на remote, создаем worktree..."
    git worktree add "$WORKTREE_DIR" "$BRANCH_NAME"
else
    echo "🆕 Ветка не существует, создаем новую ветку и worktree..."
    git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR"
fi

# Переходим в worktree
cd "$WORKTREE_DIR"

# Определяем следующий свободный порт (ищем максимальный порт и добавляем 1)
EXISTING_PORTS=$(find /Users/sollent/Desktop/Projects/CLAUDE* -name ".env.docker" -exec grep "NGINX_PORT=" {} \; 2>/dev/null | cut -d'=' -f2 | sort -n)
MAX_PORT=$(echo "$EXISTING_PORTS" | tail -1)

if [ -z "$MAX_PORT" ] || [ "$MAX_PORT" -lt 8089 ]; then
    # Если нет портов или они меньше базового, используем базовый main порт + 1
    NEXT_NGINX_PORT=8090
else
    # Иначе берем максимальный + 1
    NEXT_NGINX_PORT=$((MAX_PORT + 1))
fi

# Рассчитываем остальные порты на основе offset от базового порта
PORT_OFFSET=$((NEXT_NGINX_PORT - 8089))
NEXT_POSTGRES_PORT=$((15432 + PORT_OFFSET))
NEXT_PHP_FPM_PORT=$((9009 + PORT_OFFSET))
NEXT_FRONTEND_PORT=$((3000 + PORT_OFFSET))

echo ""
echo "🔧 Конфигурация портов:"
echo "   Nginx:      $NEXT_NGINX_PORT"
echo "   PostgreSQL: $NEXT_POSTGRES_PORT"
echo "   PHP-FPM:    $NEXT_PHP_FPM_PORT"
echo "   Frontend:   $NEXT_FRONTEND_PORT"

# Создаем .env.docker
cat > .env.docker <<EOF
# Git Worktree Configuration
# Worktree: $WORKTREE_NAME
# Branch: $BRANCH_NAME
# Auto-generated by worktree-create.sh on $(date +%Y-%m-%d)

# Docker Compose Project Name (для изоляции контейнеров)
COMPOSE_PROJECT_NAME=claude-${WORKTREE_NAME}

# PostgreSQL Configuration
POSTGRES_DB=backend-app-${WORKTREE_NAME}
POSTGRES_USER=user
POSTGRES_PASSWORD=password
POSTGRES_PORT=${NEXT_POSTGRES_PORT}

# RabbitMQ Configuration
RABBITMQ_USER=user
RABBITMQ_PASSWORD=password
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672

# Nginx Configuration
NGINX_PORT=${NEXT_NGINX_PORT}

# PHP-FPM Configuration
PHP_FPM_PORT=${NEXT_PHP_FPM_PORT}

# Frontend Configuration (если используется Docker)
FRONTEND_PORT=${NEXT_FRONTEND_PORT}
EOF

echo "✅ Файл .env.docker создан"

# Копируем .env.docker.example для справки (если не существует)
if [ ! -f .env.docker.example ]; then
    cp "$MAIN_DIR/.env.docker.example" .env.docker.example 2>/dev/null || true
fi

echo ""
echo "✅ Worktree успешно создан!"
echo ""
echo "📋 Следующие шаги:"
echo ""
echo "1. Перейти в worktree:"
echo "   cd $WORKTREE_DIR"
echo ""
echo "2. Запустить Docker контейнеры:"
echo "   docker-compose up -d"
echo ""
echo "3. Установить зависимости:"
echo "   docker exec backend-php83 composer install"
echo ""
echo "4. Создать базу данных:"
echo "   docker exec backend-php83 php bin/console doctrine:database:create"
echo ""
echo "5. Запустить миграции:"
echo "   docker exec backend-php83 php bin/console doctrine:migrations:migrate"
echo ""
echo "6. (Опционально) Загрузить fixtures:"
echo "   docker exec backend-php83 php bin/console doctrine:fixtures:load"
echo ""
echo "🌐 URL доступа:"
echo "   Backend API:  http://localhost:$NEXT_NGINX_PORT/api"
echo "   Frontend:     http://localhost:$NEXT_FRONTEND_PORT"
echo "   PostgreSQL:   localhost:$NEXT_POSTGRES_PORT"
echo ""
echo "🚀 Для запуска Claude Code:"
echo "   cd $WORKTREE_DIR && claude-code"
echo ""
