<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251117203549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE voice_commands (status VARCHAR(255) NOT NULL, command_type VARCHAR(255) NOT NULL, raw_audio_url VARCHAR(255) DEFAULT NULL, transcribed_text TEXT DEFAULT NULL, transcription_result JSON DEFAULT NULL, parsed_command JSON DEFAULT NULL, execution_result JSON DEFAULT NULL, error_message TEXT DEFAULT NULL, processing_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, processing_duration_ms INT DEFAULT NULL, metadata JSON DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F361A529A76ED395 ON voice_commands (user_id)');
        $this->addSql('CREATE INDEX idx_voice_commands_user_status ON voice_commands (user_id, status)');
        $this->addSql('CREATE INDEX idx_voice_commands_status_created ON voice_commands (status, created_at)');
        $this->addSql('ALTER TABLE voice_commands ADD CONSTRAINT FK_F361A529A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE voice_commands DROP CONSTRAINT FK_F361A529A76ED395');
        $this->addSql('DROP TABLE voice_commands');
    }
}
