<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251111150822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT DEFAULT NULL, old_data JSON DEFAULT NULL, new_data JSON DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_audit_user ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_logs (action)');
        $this->addSql('CREATE INDEX idx_audit_created_at ON audit_logs (created_at)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_task_user_parent ON task (user_id, parent_task_id)');
        $this->addSql('CREATE INDEX idx_task_user_status ON task (user_id, status)');
        $this->addSql('CREATE INDEX idx_task_user_priority ON task (user_id, priority)');
        $this->addSql('CREATE INDEX idx_task_user_archived ON task (user_id, is_archived)');
        $this->addSql('CREATE INDEX idx_task_user_due_date ON task (user_id, due_date)');
        $this->addSql('CREATE INDEX idx_task_user_completed_at ON task (user_id, completed_at)');
        $this->addSql('CREATE INDEX idx_task_user_created_at ON task (user_id, created_at)');
        $this->addSql('CREATE INDEX idx_task_user_parent_archived ON task (user_id, parent_task_id, is_archived)');
        $this->addSql('CREATE INDEX idx_task_user_parent_status ON task (user_id, parent_task_id, status)');
        $this->addSql('CREATE INDEX idx_task_user_status_archived ON task (user_id, status, is_archived)');
        $this->addSql('CREATE INDEX idx_task_user_due_status ON task (user_id, due_date, status)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP INDEX idx_task_user_parent');
        $this->addSql('DROP INDEX idx_task_user_status');
        $this->addSql('DROP INDEX idx_task_user_priority');
        $this->addSql('DROP INDEX idx_task_user_archived');
        $this->addSql('DROP INDEX idx_task_user_due_date');
        $this->addSql('DROP INDEX idx_task_user_completed_at');
        $this->addSql('DROP INDEX idx_task_user_created_at');
        $this->addSql('DROP INDEX idx_task_user_parent_archived');
        $this->addSql('DROP INDEX idx_task_user_parent_status');
        $this->addSql('DROP INDEX idx_task_user_status_archived');
        $this->addSql('DROP INDEX idx_task_user_due_status');
    }
}
